# fly.toml app configuration file generated for odin-mini-message-board-wandering-dew-2883 on 2024-08-13T14:53:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odin-mini-message-board-wandering-dew-2883'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
